### ISSUE TITLE
Gates does not work in spawn regions

### ISSUE THREAD

**Issue by sternskr** [stargate-bukkit/Stargate-Bukkit#27] opened 2021-05-06 06:01 UTC
There is a singular portal in my world that ceases to function whenever a server operator exists regardless of permissions set. This occurs if ANY op is set regardless of who & whether or not they are online.

Disabling op immediately fixes the gate for everyone. Granting stargate.* to everyone does nothing.

Nothing in the server logs with both debug options enabled indicates anything is wrong, has normal outputs saying user's have the permissions needed. Nothing denies it functioning

Things tried:
- I've tried replacing the gate with default layout nether.gate & issue persists.
- Different names do nothing. 
- Moving the gate back 3 blocks doesn't work.

Original layout of the problem gate:
![image](https://user-images.githubusercontent.com/14317840/117248284-56d80800-ae05-11eb-85dd-3d931439d9ae.png)

This is the config I have that exhibits this issue:
![image](https://user-images.githubusercontent.com/14317840/117248351-6eaf8c00-ae05-11eb-9bff-8ab48a8345a3.png)

**Comment by Pheotis** [comment] 2021-05-06 23:16
### This is certainly an odd issue… off-hand, I can’t think of anything that might explain the observed behavior.
### From what I can tell, vanilla operator statuses (including `NOT_OP`, `OP`, `isOP`, and `getOperators`) are not called, checked, or used anywhere in the plugin.
<br>

#### Unfortunately, we will probably need some more information to successfully reproduce the problem:

-----------------------------------------------------------------------------
> ### There is a singular portal in my world that ceases to function whenever a server operator exists regardless of permissions set.
- What is unique about this portal in particular? What distinguishes it from other (working) portals?
  - What is the portal's name, destination, flags, network, and owner/creator?
    - Can an identical portal be recreated elsewhere?
  - Are there any notable properties about this portal's location?
    - Is the area within your spawn chunks? Do any plugins impact this area in particular?
    - Does moving the portal elsewhere (i.e. to another chunk or elsewhere on the map) change anything?
> ### Disabling op immediately fixes the gate for everyone. Granting stargate.* to everyone does nothing.
- Given that OP isn't checked, and that the issue persists, this might signify a compatibility issue.
  - Was an OP'd user the one who made the portal? What permissions did they have?
    - Can that same user make an identical portal elsewhere?
- What key (i.e. permission and/or block-impacting) plugins do you use with your server?
  - (If it is not too much effort), can the issue be replicated with stargate alone (i.e. disable everything else)?
    - If stargate works alone, slowly [re-enable](https://en.wikipedia.org/wiki/Binary_search_algorithm) plugins until you find the conflict.
> ### Nothing in the server logs with both debug options enabled indicates anything is wrong, has normal outputs saying user's have the permissions needed. Nothing denies it functioning
- If possible, can you please provide a [copy](https://hastebin.com/) of the relevant logs
  - If you have an advanced permission plugin, try a [verbose](https://luckperms.net/verbose/) trace when creating and/or using the portal.
- How precisely does it fail to function?
  - What happens once a portal is activated? Is the portal-open material placed?
  - What happens if a player attempts to enter the portal?
  - Does the portal work if it is created with the `A` flag?

**Comment by Pheotis** [comment] 2021-05-07 00:07
Also, it looks like you are importing from another stargate fork.
That fork may have made some database formatting changes that are incompatible with SG10.

![image](https://user-images.githubusercontent.com/49039536/117379905-8c80fd80-aea6-11eb-853a-e9a03624db16.png)

Did the problematic portal exist before you imported? Were there any other portals in the area?

**Comment by sternskr** [comment] 2021-05-07 00:42
I believe I started without any DBs from older forks as they didn't import properly anyway. This is an old server from 1.10 that I'm resurrecting so it's been a slow process & I can't say for sure. This is the only piece that seems to still cause issues

However, I can say for sure no gates imported properly and all of them had to be remade by hand
There is another gate one chunk away that works properly

I'll try changing my config over to the newer format & see if that helps

I can also attach the entire Stargate folder if that's helpful, is there anything identifiable stored in the .dbs? Want to know before I throw a .zip up

**Comment by sternskr** [comment] 2021-05-07 02:28
Here's a video replicating the problem:
https://www.youtube.com/watch?v=yDujgxxPDLI

0:00​ - gate working before OP
0:18​ - make someone else OP
0:32​ - original gate not working
0:52​ - alternate gate still functioning
1:08​ - de-oping other player, so there are NO server OPs
1:18​ - gate working again

**Comment by Thorinwasher** [comment] 2021-05-07 12:39
If the portal is at the spawnchunks then this might be related to spawn protection:

This is a vanilla feature that  functions like this: If anyone is oped at the server, then the spawnchunks will be protected, else they wont be protected.

This could be resolved by:
- disabling spawn protection in the server.properties file (more about this in https://minecraft.fandom.com/wiki/Spawn_protection ).
-  Move the portal out of the spawnregion.

We will look into other solutions to fix this, if the portal is at spawn so to say. But plugins are not allowed to mess with spawnprotection

**Comment by Thorinwasher** [comment] 2021-06-11 15:07
There is kind of already an solution for this on serverside and it also seems tricky to implement; so I'm going to close this, for now

**Comment by Pheotis** [comment] 2021-07-12 14:37
We found a problem with commit d107656
Reopening this issue to fix it.

**Closed** 2021-07-12 15:10 UTC
Labels: enhancement
